language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
matrix:
  fast_finish: true
install:
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
notifications:
  irc: irc.freenode.org#plone-testing
